import type {
  Vehicle,
  Trip,
  DashboardStats,
  MonthlyData,
  AnalyticsData,
} from "./types";

export const mockVehicles: Vehicle[] = [
  {
    id: "v1",
    name: "Toyota Avanza",
    type: "SEDAN",
    licensePlate: "B1234ABC",
    status: "ACTIVE",
    driverId: "d1",
    driverName: "Budi Santoso",
    lastMaintenance: new Date("2024-10-15"),
    nextMaintenance: new Date("2025-01-15"),
    mileage: 45200,
    fuelConsumption: 8.5,
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "v2",
    name: "Daihatsu Gran Max",
    type: "VAN",
    licensePlate: "B5678XYZ",
    status: "ACTIVE",
    driverId: "d2",
    driverName: "Siti Nurhaliza",
    lastMaintenance: new Date("2024-09-20"),
    nextMaintenance: new Date("2024-12-20"),
    mileage: 62800,
    fuelConsumption: 12.3,
    createdAt: new Date("2022-08-15"),
    updatedAt: new Date("2024-11-08"),
  },
  {
    id: "v3",
    name: "Mitsubishi Colt Diesel",
    type: "TRUCK",
    licensePlate: "B9012TRK",
    status: "MAINTENANCE",
    driverId: "d3",
    driverName: "Ahmad Hidayat",
    lastMaintenance: new Date("2024-11-01"),
    nextMaintenance: new Date("2024-11-20"),
    mileage: 98500,
    fuelConsumption: 18.7,
    createdAt: new Date("2021-03-22"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: "v4",
    name: "Toyota Fortuner",
    type: "SUV",
    licensePlate: "B3456DEF",
    status: "ACTIVE",
    driverId: "d4",
    driverName: "Dewi Lestari",
    lastMaintenance: new Date("2024-08-10"),
    nextMaintenance: new Date("2024-12-10"),
    mileage: 34100,
    fuelConsumption: 11.2,
    createdAt: new Date("2023-05-18"),
    updatedAt: new Date("2024-11-12"),
  },
  {
    id: "v5",
    name: "Honda City",
    type: "SEDAN",
    licensePlate: "B7890GHI",
    status: "INACTIVE",
    driverId: "d5",
    driverName: "Rudi Hermawan",
    lastMaintenance: new Date("2024-07-25"),
    nextMaintenance: new Date("2024-11-25"),
    mileage: 28900,
    fuelConsumption: 7.8,
    createdAt: new Date("2023-09-05"),
    updatedAt: new Date("2024-10-30"),
  },
  {
    id: "v6",
    name: "Suzuki Carry",
    type: "VAN",
    licensePlate: "B2345JKL",
    status: "ACTIVE",
    driverId: "d6",
    driverName: "Rina Wijaya",
    lastMaintenance: new Date("2024-10-05"),
    nextMaintenance: new Date("2025-01-05"),
    mileage: 51200,
    fuelConsumption: 13.1,
    createdAt: new Date("2022-11-12"),
    updatedAt: new Date("2024-11-05"),
  },
];

export const mockTrips: Record<string, Trip[]> = {
  v1: [
    {
      id: "t1",
      vehicleId: "v1",
      startDate: new Date("2024-11-10T08:00:00"),
      endDate: new Date("2024-11-10T12:30:00"),
      distance: 125,
      fuelUsed: 10.5,
      destination: "Downtown Office",
      driverName: "Budi Santoso",
      createdAt: new Date("2024-11-10"),
    },
    {
      id: "t2",
      vehicleId: "v1",
      startDate: new Date("2024-11-09T09:15:00"),
      endDate: new Date("2024-11-09T14:45:00"),
      distance: 98,
      fuelUsed: 8.2,
      destination: "Client Meeting - North District",
      driverName: "Budi Santoso",
      createdAt: new Date("2024-11-09"),
    },
  ],
  v2: [
    {
      id: "t3",
      vehicleId: "v2",
      startDate: new Date("2024-11-11T06:30:00"),
      endDate: new Date("2024-11-11T18:00:00"),
      distance: 245,
      fuelUsed: 30.1,
      destination: "Warehouse Delivery",
      driverName: "Siti Nurhaliza",
      createdAt: new Date("2024-11-11"),
    },
  ],
};

export const mockDashboardStats: DashboardStats = {
  totalVehicles: 6,
  activeVehicles: 4,
  averageConsumption: 11.93,
  upcomingMaintenance: 3,
};

export const mockMonthlyData: MonthlyData[] = [
  { month: "Jun", mileage: 12400, activeVehicles: 5, inactiveVehicles: 1 },
  { month: "Jul", mileage: 14200, activeVehicles: 6, inactiveVehicles: 0 },
  { month: "Aug", mileage: 13800, activeVehicles: 5, inactiveVehicles: 1 },
  { month: "Sep", mileage: 15600, activeVehicles: 6, inactiveVehicles: 0 },
  { month: "Oct", mileage: 16200, activeVehicles: 5, inactiveVehicles: 1 },
  { month: "Nov", mileage: 14800, activeVehicles: 4, inactiveVehicles: 2 },
];

export const mockAnalyticsData: AnalyticsData = {
  fuelConsumption: [
    { month: "Jun", consumption: 845 },
    { month: "Jul", consumption: 920 },
    { month: "Aug", consumption: 885 },
    { month: "Sep", consumption: 975 },
    { month: "Oct", consumption: 1020 },
    { month: "Nov", consumption: 890 },
  ],
  utilizationRate: [
    { vehicle: "Avanza", rate: 85 },
    { vehicle: "Gran Max", rate: 92 },
    { vehicle: "Colt Diesel", rate: 45 },
    { vehicle: "Fortuner", rate: 78 },
    { vehicle: "Honda City", rate: 35 },
    { vehicle: "Suzuki Carry", rate: 88 },
  ],
  driverPerformance: [
    { driver: "Budi Santoso", score: 92 },
    { driver: "Siti Nurhaliza", score: 95 },
    { driver: "Ahmad Hidayat", score: 78 },
    { driver: "Dewi Lestari", score: 88 },
    { driver: "Rudi Hermawan", score: 71 },
    { driver: "Rina Wijaya", score: 91 },
  ],
};
